source "http://rubygems.org"

# Specify your gem's dependencies in muzang-motd.gemspec
gemspec

gem "muzang", :path => File.expand_path("../../muzang", __FILE__)
File.open(File.expand_path("../../.Gemfile", __FILE__)){|f|eval(f.read)}
